import { ProjectSpaceResource } from 'web-client/src/helpers'

export const spaces: ProjectSpaceResource[] = [
  {
    id: '1',
    fileId: '1',
    name: 'Some space',
    extension: '',
    path: '/',
    type: 'space',
    isFolder: false,
    mdate: 'Mon, 12 Jul 2021 11:04:33 GMT',
    size: '0',
    indicators: [],
    permissions: 'RDNVW',
    starred: false,
    etag: '"89128c0e8122002db57bd19c9ec33004"',
    shareTypes: [],
    downloadURL: '',
    disabled: false,
    canDownload: () => true,
    isReceivedShare: () => false,
    canBeDeleted: () => false,
    canRename: () => false,
    canShare: () => false,
    canDeny: () => false,
    canEditDescription: () => true,
    canEditImage: () => true,
    canDisable: () => true,
    canRestore: () => true,
    isViewer: () => true,
    isEditor: () => true,
    isManager: () => true,
    webDavTrashPath: '',
    root: {
      id: '',
      remoteItem: { id: '', name: '' },
      webDavUrl: ''
    },
    getDomSelector: jest.fn(),
    getWebDavUrl: jest.fn(),
    getWebDavTrashUrl: jest.fn(),
    getDriveAliasAndItem: jest.fn(),
    driveType: 'project'
  },
  {
    id: '2',
    fileId: '2',
    name: 'Another space',
    extension: '',
    path: '/',
    type: 'space',
    isFolder: false,
    mdate: 'Mon, 12 Jul 2021 11:04:33 GMT',
    size: '12',
    indicators: [],
    permissions: 'RDNVW',
    starred: false,
    etag: '"99128c0e8122002db57bd19c9ec33004"',
    shareTypes: [],
    downloadURL: '',
    disabled: false,
    canDownload: () => true,
    isReceivedShare: () => false,
    canBeDeleted: () => false,
    canRename: () => false,
    canShare: () => false,
    canDeny: () => false,
    canEditDescription: () => true,
    canEditImage: () => true,
    canDisable: () => true,
    canRestore: () => true,
    isViewer: () => true,
    isEditor: () => true,
    isManager: () => true,
    webDavTrashPath: '',
    root: {
      id: '',
      remoteItem: { id: '', name: '' },
      webDavUrl: ''
    },
    getDomSelector: jest.fn(),
    getWebDavUrl: jest.fn(),
    getWebDavTrashUrl: jest.fn(),
    getDriveAliasAndItem: jest.fn(),
    driveType: 'project'
  },
  {
    id: '3',
    fileId: '3',
    name: 'Disabled space',
    extension: '',
    path: '/',
    type: 'space',
    isFolder: false,
    mdate: 'Mon, 12 Jul 2021 11:04:33 GMT',
    size: '12',
    indicators: [],
    permissions: 'RDNVW',
    starred: false,
    etag: '"69128c0e8122002db57bd19c9ec33004"',
    shareTypes: [],
    downloadURL: '',
    disabled: true,
    canDownload: () => true,
    isReceivedShare: () => false,
    canBeDeleted: () => false,
    canRename: () => false,
    canShare: () => false,
    canDeny: () => false,
    canEditDescription: () => true,
    canEditImage: () => true,
    canDisable: () => true,
    canRestore: () => true,
    isViewer: () => true,
    isEditor: () => true,
    isManager: () => true,
    webDavTrashPath: '',
    root: {
      id: '',
      remoteItem: { id: '', name: '' },
      webDavUrl: ''
    },
    getDomSelector: jest.fn(),
    getWebDavUrl: jest.fn(),
    getWebDavTrashUrl: jest.fn(),
    getDriveAliasAndItem: jest.fn(),
    driveType: 'project'
  }
]
