workspace:
  base: /var/www/owncloud
  path: phoenix

branches: [master, release*, develop*]

pipeline:
  build-docker-image:
    image: toolhippie/docker:latest
    pull: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t owncloud/phoenix:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} .
    when:
      event: [ push ]
      matrix:
        AFTER_JOB: true

  npm-install:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - yarn install

  build-phoenix:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - yarn dist
      - cp tests/drone/config.json dist/config.json
    when:
      matrix:
        RUN_PHOENIX: true

  lint-test:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/phoenix
      - yarn run lint
    when:
      matrix:
        TEST_SUITE: lint-test

  install-server:
    image: owncloudci/core
    version: ${OC_VERSION=daily-master-qa}
    pull: true
    db_type: ${DB_TYPE=sqlite}
    db_name: ${DB_NAME=sqlite}
    db_host: ${DB_TYPE=sqlite}
    db_username: autotest
    db_password: owncloud
    core_path: /var/www/owncloud/
    when:
      matrix:
        NEED_SERVER: true

  clone-oauth:
    image: owncloud/ubuntu:16.04
    pull: true
    commands:
      - git clone -b master https://github.com/owncloud/oauth2.git /var/www/owncloud/apps/oauth2
    when:
      matrix:
        NEED_SERVER: true

  configure-server:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:e testing
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ config:system:set cors.allowed-domains 0 --value=http://phoenix:8300
      - php occ log:manage --level 0
      - php occ config:list
      - php occ a:e oauth2
      - php occ oauth2:add-client Phoenix Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU 930C6aA0U1VhM03IfNiheR2EwSzRi4hRSpcNqIhhbpeSGU6h38xssVfNcGP0sSwQ http://phoenix:8300/oidc-callback.html
      - php occ config:system:set skeletondirectory --value=/var/www/owncloud/apps/testing/data/webUISkeleton
    when:
      matrix:
        NEED_SERVER: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log
    when:
      matrix:
        NEED_SERVER: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - chown www-data * -R
    when:
      matrix:
        NEED_SERVER: true

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    environment:
      - TEST_CONTEXT=${TEST_CONTEXT}
      - SCREEN_RESOLUTION=${SCREEN_RESOLUTION}
      - TEST_TAGS=${TEST_TAGS}
    commands:
      - cd /var/www/owncloud/phoenix
      - curl http://phoenix:8300/oidc-callback.html
      - yarn run acceptance-tests-drone
    when:
      matrix:
        TEST_SUITE: acceptance

  upload-screenshots:
    image: plugins/s3
    bucket: phoenix
    acl: public-read
    source: /var/www/owncloud/phoenix/tests/reports/screenshots/**/*
    target: /screenshots/${DRONE_BUILD_NUMBER}
    path_style: true
    endpoint: https://minio.owncloud.com/
    strip_prefix: /var/www/owncloud/phoenix/tests/reports/screenshots
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      status: [ failure ]
      matrix:
        TEST_SUITE: acceptance

  build-github-comment:
    image: owncloud/ubuntu:16.04
    pull: true
    environment:
      - TEST_CONTEXT=${TEST_CONTEXT}
    commands:
      - cd /var/www/owncloud/phoenix/tests/reports/screenshots/
      - 'echo "<details><summary>:boom: Acceptance tests <strong>${TEST_CONTEXT}</strong> failed. Please find the screenshots inside ...</summary>\n\n${DRONE_BUILD_LINK}/${DRONE_JOB_NUMBER}\n\n<p>\n\n" >> comments.file'
      - for f in *.png; do echo '!'"[$f](https://minio.owncloud.com/phoenix/screenshots/${DRONE_BUILD_NUMBER}/$f)" >> comments.file; done
      - echo "\n</p></details>" >> comments.file
      - more comments.file
    when:
      status: [ failure ]
      matrix:
        TEST_SUITE: acceptance

  github-comment:
    image: jmccann/drone-github-comment:1
    secrets: [ plugin_api_key ]
    message_file: /var/www/owncloud/phoenix/tests/reports/screenshots/comments.file
    when:
      status: [ failure ]
      matrix:
        TEST_SUITE: acceptance

  build-release:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/phoenix
      - make -f Makefile.release dist
    when:
      event: [ push ]
      matrix:
        AFTER_JOB: true

  deploy-staging:
    image: drillster/drone-rsync:latest
    pull: true
    secrets: [ rsync_key ]
    user: deploy
    hosts: pixie.owncloud.systems
    port: 22
    recursive: true
    delete: true
    source: dist/
    target: /home/deploy/phoenix
    script:
      - sudo docker exec phoenix occ maintenance:mode --on
      - sudo rsync -az --chown=www-data:www-data -r --del --exclude config.json /home/deploy/phoenix/ /var/lib/phoenix/apps/phoenix
      - sudo docker exec phoenix occ maintenance:mode --off
      - sudo docker exec phoenix owncloud migrate
    when:
      event: [ push ]
      branch: [ master ]
      matrix:
        AFTER_JOB: true

services:
  phoenix:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - mkdir dist
      - make run SERVER_HOST=phoenix:8300
    when:
      matrix:
        RUN_PHOENIX: true

  owncloud:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        NEED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: acceptance

  docker:
    image: docker:18.04-dind
    when:
      matrix:
        AFTER_JOB: true

matrix:
  include:
    # lint test
    - TEST_SUITE: lint-test

    # acceptance test
    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIAdminSettings
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIComments
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIFavorites
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIFiles
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUILogin
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIMoveFilesFolders
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUINotifications
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIRenameFiles
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIRenameFolders
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIRestrictSharing
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUISharingAcceptShares
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUISharingExternal
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUISharingInternalGroups
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUISharingInternalUsers
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUISharingNotifications
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUISharingPublic
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUITags
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUITrashbin
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIUpload
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIWebdavLockProtection
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUIWebdavLocks
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_CONTEXT: webUITags
      TEST_TAGS: 'not @skip'

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_TAGS: '@smokeTest and not @skipOnXGAPortraitResolution and not @skip'
      SCREEN_RESOLUTION: 768x1024

    - TEST_SUITE: acceptance
      NEED_SERVER: true
      RUN_PHOENIX: true
      TEST_TAGS: '@smokeTest and not @skipOnIphoneResolution and not @skip'
      SCREEN_RESOLUTION: 375x812

    # After drone all jobs completes
    - AFTER_JOB: true
