import('@toast-ui/editor/dist/i18n/ar')
import('@toast-ui/editor/dist/i18n/cs-cz')
import('@toast-ui/editor/dist/i18n/de-de')
import('@toast-ui/editor/dist/i18n/en-us')
import('@toast-ui/editor/dist/i18n/es-es')
import('@toast-ui/editor/dist/i18n/fi-fi')
import('@toast-ui/editor/dist/i18n/fr-fr')
import('@toast-ui/editor/dist/i18n/gl-es')
import('@toast-ui/editor/dist/i18n/hr-hr')
import('@toast-ui/editor/dist/i18n/it-it')
import('@toast-ui/editor/dist/i18n/ja-jp')
import('@toast-ui/editor/dist/i18n/ko-kr')
import('@toast-ui/editor/dist/i18n/nb-no')
import('@toast-ui/editor/dist/i18n/nl-nl')
import('@toast-ui/editor/dist/i18n/pl-pl')
import('@toast-ui/editor/dist/i18n/ru-ru')
import('@toast-ui/editor/dist/i18n/sv-se')
import('@toast-ui/editor/dist/i18n/tr-tr')
import('@toast-ui/editor/dist/i18n/uk-ua')
import('@toast-ui/editor/dist/i18n/zh-cn')
import('@toast-ui/editor/dist/i18n/zh-tw')

export default {}
