directives:
  child-src:
    - '''self'''
    - 'blob:'
  connect-src:
    - '''self'''
  default-src:
    - '''none'''
  font-src:
    - '''self'''
  frame-ancestors:
    - '''self'''
  frame-src:
    - '''self'''
    - 'blob:'
    - 'https://embed.diagrams.net/'
    # In contrast to bash and docker the default is given after the | character
    - 'https://${ONLYOFFICE_DOMAIN|host.docker.internal:9981}/'
    - 'https://${COLLABORA_DOMAIN|host.docker.internal:9980}/'
  img-src:
    - '''self'''
    - 'data:'
    - 'blob:'
    # In contrast to bash and docker the default is given after the | character
    - 'https://${ONLYOFFICE_DOMAIN|host.docker.internal:9981}/'
    - 'https://${COLLABORA_DOMAIN|host.docker.internal:9980}/'
  manifest-src:
    - '''self'''
  media-src:
    - '''self'''
  object-src:
    - '''self'''
    - 'blob:'
  script-src:
    - '''self'''
    - '''unsafe-inline'''
    - '''wasm-unsafe-eval'''
  style-src:
    - '''self'''
    - '''unsafe-inline'''
