import { configureCompat } from 'vue'

type CompatConfig = Parameters<typeof configureCompat>[0]
export const compatConfig: CompatConfig = {
  MODE: 2,
  // ATTR_ENUMERATED_COERCION: false,
  // ATTR_FALSE_VALUE: false,
  // COMPONENT_ASYNC: false,
  // COMPONENT_FUNCTIONAL: false,
  // COMPONENT_V_MODEL: false,
  // CONFIG_DEVTOOLS: false,
  // CONFIG_IGNORED_ELEMENTS: false,
  // CONFIG_KEY_CODES: false,
  // CONFIG_OPTION_MERGE_STRATS: false,
  // CONFIG_PRODUCTION_TIP: false,
  // CONFIG_SILENT: false,
  // CONFIG_WHITESPACE: false,
  // CUSTOM_DIR: false,
  // FILTERS: false,
  // GLOBAL_DELETE: false,
  // GLOBAL_EXTEND: false,
  // GLOBAL_MOUNT: false,
  // GLOBAL_MOUNT_CONTAINER: false,
  // GLOBAL_OBSERVABLE: false,
  // GLOBAL_PRIVATE_UTIL: false,
  // GLOBAL_PROTOTYPE: false,
  // GLOBAL_SET: false,
  // INSTANCE_ATTRS_CLASS_STYLE: false,
  // INSTANCE_CHILDREN: false,
  // INSTANCE_DELETE: false,
  // INSTANCE_DESTROY: false,
  // INSTANCE_EVENT_EMITTER: false,
  // INSTANCE_EVENT_HOOKS: false,
  // INSTANCE_LISTENERS: false,
  // INSTANCE_SCOPED_SLOTS: false,
  // INSTANCE_SET: false,
  // OPTIONS_BEFORE_DESTROY: false,
  // OPTIONS_DATA_FN: false,
  // OPTIONS_DATA_MERGE: false,
  // OPTIONS_DESTROYED: false,
  // PRIVATE_APIS: false,
  // PROPS_DEFAULT_THIS: false,
  // RENDER_FUNCTION: false // comment in when vue-router, vue-gettext, ... are fixed/updated
  // TRANSITION_CLASSES: false,
  // TRANSITION_GROUP_ROOT: false,
  // V_ON_KEYCODE_MODIFIER: false,
  // WATCH_ARRAY: false,
}
