export default {
  'oc-spinner': true,
  'oc-grid': true,
  'oc-icon': true,
  'oc-checkbox': true,
  'oc-button': true,
  'oc-breadcrumb': true,
  'oc-drop': true,
  'avatar-image': true,
  'oc-hidden-announcer': true,
  translate: true,
  'oc-list': true,
  'oc-switch': true,
  'oc-loader': true,
  'oc-img': true,
  'oc-page-size': true,
  'router-link': true,
  'portal-target': true,
  'oc-progress': true
}
