export const EVENT_THEAD_CLICKED = 'thead-clicked'
export const EVENT_TROW_CLICKED = 'highlight'
export const EVENT_TROW_MOUNTED = 'rowMounted'
export const EVENT_TROW_CONTEXTMENU = 'contextmenuClicked'
export const EVENT_ITEM_DROPPED = 'itemDropped'
export const EVENT_ITEM_DRAGGED = 'itemDragged'
export const EVENT_FILE_DROPPED = 'fileDropped'
