name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 10.33.3

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check licenses
        run: pnpm licenses:check

      - name: Save licenses
        run: pnpm licenses:csv && pnpm licenses:save

      - name: Check types
        run: pnpm check:types

      - name: Check format
        run: pnpm check:format

      - name: Lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:unit --coverage

      - name: Build
        run: make dist

      - name: Store build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: web-dist
          path: dist
          if-no-files-found: error
