name: changelog

on:
  push:
    branches:
      - master
      - stable-*
  pull_request:
    branches:
      - master
      - stable-*

permissions:
  contents: read

jobs:
  changelog:
    uses: owncloud/reusable-workflows/.github/workflows/calens.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
