name: Test and build

on:
  push:
    branches:
      - master
      - stable-*
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10.29.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.14.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check licenses
        run: pnpm licenses:check

      - name: Save licenses
        run: pnpm licenses:csv && pnpm licenses:save

      - name: Check types
        run: pnpm check:types

      - name: Check format
        run: pnpm check:format

      - name: Lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:unit --coverage

      - name: SonarCloud Scan
        if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/')
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PULL_REQUEST_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || '' }}
          SONAR_PULL_REQUEST_BRANCH: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || '' }}
          SONAR_PULL_REQUEST_KEY: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || '' }}

      - name: Build
        run: make dist

      - name: Store build artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: web-dist
          path: dist
          if-no-files-found: error

  e2e-playwright:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suites:
          - admin-settings
          - app-provider
          - app-store
          - file-action
          - navigation
          - ocm
          - oidc
          - runtime
          - search
          - shares
          - smoke
          - user-settings
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: web-dist
          path: dist

      - name: Run oCIS
        run: |
          docker run -d \
            --name ocis \
            -p 9200:9200 \
            -v ${{ github.workspace }}:/workspace \
            -e IDM_ADMIN_PASSWORD=admin \
            -e OCIS_INSECURE=true \
            -e OCIS_LOG_LEVEL=error \
            -e OCIS_JWT_SECRET=some-ocis-jwt-secret \
            -e LDAP_GROUP_SUBSCRIPTION_FILTER_TYPE=any \
            -e LDAP_USER_SUBSCRIPTION_FILTER_TYPE=any \
            -e PROXY_ENABLE_BASIC_AUTH=true \
            -e WEB_ASSET_CORE_PATH=/workspace/dist \
            -e FRONTEND_SEARCH_MIN_LENGTH=2 \
            -e OCIS_PASSWORD_POLICY_BANNED_PASSWORDS_LIST=/workspace/tests/drone/banned-passwords.txt \
            -e PROXY_CSP_CONFIG_FILE_LOCATION=/workspace/tests/drone/csp.yaml \
            -e GRAPH_AVAILABLE_ROLES=b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6,63e64e19-8d43-42ec-a738-2b6af2610efa \
            -e FRONTEND_CONFIGURABLE_NOTIFICATIONS=true \
            -e OCIS_URL=https://localhost:9200 \
            -e WEB_UI_CONFIG_FILE=/workspace/tests/drone/config-ocis.json \
            owncloud/ocis-rolling:latest

      - name: Wait for oCIS service
        run: |
          echo "Waiting for oCIS"
          # 150s timeout
          for i in {1..30}; do
            if curl -kfsSL https://localhost:9200 > /dev/null; then
              echo "oCIS is up ✅"
              exit 0
            fi
            echo "Retrying in 5s..."
            sleep 5
          done
          echo "❌ oCIS failed to start"
          docker logs ocis
          docker inspect ocis
          exit 1

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 10.29.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Cache Playwright browsers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm dlx playwright install --with-deps chromium

      - name: Install system deps if cache hit
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm dlx playwright install-deps chromium

      - name: Run E2E tests
        run: cd ${{ github.workspace }}/tests/e2e && run-e2e.sh --type playwright --suites ${{ matrix.suites }}
